#!/bin/bash
# Generate CHANGELOG from git history
# Usage: ./changelog.sh

set -e

# Get last tag or empty
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

echo "# Changelog"
echo ""
echo "All notable changes to this project will be documented in this file."
echo ""

# Categorize commit message
get_category() {
    local msg="$1"
    msg_lower=$(echo "$msg" | tr '[:upper:]' '[:lower:]')
    
    if [[ "$msg_lower" =~ ^(feat|feature|add|new): ]]; then echo "Added"
    elif [[ "$msg_lower" =~ ^(fix|bugfix|hotfix|patch): ]]; then echo "Fixed"
    elif [[ "$msg_lower" =~ ^(change|update|refactor|improve|perf|optimize): ]]; then echo "Changed"
    elif [[ "$msg_lower" =~ ^(remove|delete|deprecate|drop): ]]; then echo "Removed"
    else echo "Other"
    fi
}

# Clean message (remove conventional commit prefix)
clean_msg() {
    echo "$1" | sed -E 's/^(feat|feature|add|fix|bugfix|hotfix|change|update|refactor|improve|perf|optimize|remove|delete|deprecate|drop|new|patch):[[:space:]]*//i'
}

echo "## [Unreleased]"
echo ""

# Get commits since last tag
if [ -n "$LAST_TAG" ]; then
    commits=$(git log "$LAST_TAG"..HEAD --pretty=format:"%s" --no-merges 2>/dev/null)
else
    commits=$(git log --pretty=format:"%s" --no-merges 2>/dev/null)
fi

# Collect commits by category
added=""
fixed=""
changed=""
removed=""
other=""

while IFS= read -r msg; do
    [ -z "$msg" ] && continue
    cat=$(get_category "$msg")
    clean=$(clean_msg "$msg")
    line="- $clean"
    
    case "$cat" in
        Added) added="${added}${line}\n" ;;
        Fixed) fixed="${fixed}${line}\n" ;;
        Changed) changed="${changed}${line}\n" ;;
        Removed) removed="${removed}${line}\n" ;;
        Other) other="${other}${line}\n" ;;
    esac
done <<< "$commits"

# Output categories with content
if [ -n "$added" ]; then echo "### Added"; echo -e "$added"; fi
if [ -n "$fixed" ]; then echo "### Fixed"; echo -e "$fixed"; fi
if [ -n "$changed" ]; then echo "### Changed"; echo -e "$changed"; fi
if [ -n "$removed" ]; then echo "### Removed"; echo -e "$removed"; fi
if [ -n "$other" ]; then echo "### Other"; echo -e "$other"; fi

# Add recent tags
for tag in $(git tag --sort=-v:refname 2>/dev/null | head -5); do
    date=$(git log -1 --format=%ai "$tag" 2>/dev/null | cut -d' ' -f1)
    echo ""
    echo "## [$tag] - $date"
done

echo ""
echo "---"
echo "Generated by generate-changelog skill"