#!/usr/bin/env python3
"""
Claude Code PR Review Agent
Analyzes GitHub PRs and generates structured review comments.

Usage:
    claude-review --pr https://github.com/owner/repo/pull/123
    claude-review --pr owner/repo/123
    claude-review --diff changes.diff --repo owner/repo

Output: Structured Markdown review comment
"""

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from typing import Optional
import urllib.request
import urllib.error


@dataclass
class ReviewResult:
    """Structured review output"""
    summary: str
    risks: list[str]
    suggestions: list[str]
    confidence: str  # Low, Medium, High
    
    def to_markdown(self) -> str:
        """Convert to GitHub-flavored Markdown"""
        md = f"""## 🤖 Automated PR Review

### Summary
{self.summary}

### ⚠️ Identified Risks
"""
        if self.risks:
            for risk in self.risks:
                md += f"- {risk}\n"
        else:
            md += "- No significant risks identified\n"
        
        md += "\n### 💡 Improvement Suggestions\n"
        if self.suggestions:
            for suggestion in self.suggestions:
                md += f"- {suggestion}\n"
        else:
            md += "- No specific suggestions\n"
        
        md += f"""
### 📊 Confidence: {self.confidence}

---
*Generated by Claude Review Agent*
"""
        return md


def parse_pr_url(url: str) -> tuple[str, str, int]:
    """Parse GitHub PR URL into owner, repo, and PR number"""
    # Handle various formats
    patterns = [
        r"github\.com/([^/]+)/([^/]+)/pull/(\d+)",
        r"github\.com/([^/]+)/([^/]+)/pulls/(\d+)",
    ]
    
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            owner, repo, pr_num = match.groups()
            # Remove .git suffix if present
            repo = repo.replace(".git", "")
            return owner, repo, int(pr_num)
    
    raise ValueError(f"Invalid PR URL format: {url}")


def fetch_pr_diff(owner: str, repo: str, pr_number: int, token: Optional[str] = None) -> str:
    """Fetch PR diff from GitHub API"""
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}"
    
    headers = {
        "Accept": "application/vnd.github.v3.diff",
        "User-Agent": "claude-review-agent/1.0"
    }
    
    if token:
        headers["Authorization"] = f"token {token}"
    
    req = urllib.request.Request(url, headers=headers)
    
    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            return response.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        if e.code == 404:
            raise ValueError(f"PR not found: {owner}/{repo}#{pr_number}")
        elif e.code == 403:
            raise ValueError("Rate limited. Set GITHUB_TOKEN environment variable.")
        raise


def fetch_pr_info(owner: str, repo: str, pr_number: int, token: Optional[str] = None) -> dict:
    """Fetch PR metadata (title, author, etc.)"""
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}"
    
    headers = {
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "claude-review-agent/1.0"
    }
    
    if token:
        headers["Authorization"] = f"token {token}"
    
    req = urllib.request.Request(url, headers=headers)
    
    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        if e.code == 404:
            raise ValueError(f"PR not found: {owner}/{repo}#{pr_number}")
        raise


def analyze_diff(diff: str, pr_info: dict) -> ReviewResult:
    """Analyze PR diff and generate review"""
    # Parse diff into sections
    files_changed = []
    additions = 0
    deletions = 0
    risks = []
    suggestions = []
    
    current_file = None
    hunks = []
    
    for line in diff.split("\n"):
        if line.startswith("+++ b/"):
            current_file = line[6:]
            files_changed.append(current_file)
        elif line.startswith("+") and not line.startswith("+++"):
            additions += 1
        elif line.startswith("-") and not line.startswith("---"):
            deletions += 1
        
        # Security patterns
        if any(pattern in line.lower() for pattern in ["password", "secret", "api_key", "apikey", "token"]):
            if not line.strip().startswith("#") and "=" in line:
                risks.append(f"Possible hardcoded credential in `{current_file or 'unknown'}`")
        
        # SQL injection risk
        if "execute(" in line or "query(" in line or "raw(" in line:
            if "select" in line.lower() or "insert" in line.lower():
                risks.append(f"Potential SQL injection in `{current_file or 'unknown'}` - use parameterized queries")
        
        # Command injection
        if "exec(" in line or "system(" in line or "shell(" in line or "subprocess.call(" in line:
            if "+" in line or "format(" in line or f"f'" in line:
                risks.append(f"Potential command injection in `{current_file or 'unknown'}`")
        
        # TODO/FIXME detection
        if "TODO" in line or "FIXME" in line or "XXX" in line:
            suggestions.append(f"Resolve TODO/FIXME in `{current_file or 'unknown'}`")
    
    # File-based analysis
    for file in files_changed:
        # Large changes
        if additions > 500:
            risks.append(f"Large PR ({additions} additions) - consider breaking into smaller PRs")
            break
    
    # Test coverage check
    test_files = [f for f in files_changed if "test" in f.lower() or f.endswith(("_test.py", "test.py", ".test.js", ".spec.js"))]
    source_files = [f for f in files_changed if not f.startswith("test") and "test" not in f.lower()]
    
    if source_files and not test_files and additions > 50:
        suggestions.append("Consider adding tests for the changes")
    
    # Documentation check
    doc_files = [f for f in files_changed if f.endswith((".md", ".rst", ".txt")) or "doc" in f.lower()]
    if source_files and not doc_files and additions > 100:
        suggestions.append("Consider documenting the changes")
    
    # Generate summary
    file_count = len(files_changed)
    if file_count == 0:
        summary = "Empty PR with no file changes."
    elif file_count == 1:
        summary = f"This PR modifies `{files_changed[0]}` with {additions} additions and {deletions} deletions."
    else:
        summary = f"This PR modifies {file_count} files with {additions} additions and {deletions} deletions. "
        if file_count <= 5:
            summary += f"Files: {', '.join(f'`{f}`' for f in files_changed[:5])}."
        else:
            summary += f"Key files: {', '.join(f'`{f}`' for f in files_changed[:3])}, and {file_count - 3} more."
    
    # Determine confidence
    if additions + deletions < 50:
        confidence = "High"
    elif additions + deletions < 200:
        confidence = "Medium"
    else:
        confidence = "Low"
    
    # Adjust for risk count
    if len(risks) > 2:
        confidence = "Low"
    
    # Add PR title context
    if pr_info.get("title"):
        summary = f"**{pr_info['title']}**\n\n" + summary
    
    return ReviewResult(
        summary=summary,
        risks=risks[:5],  # Limit to top 5
        suggestions=suggestions[:5],  # Limit to top 5
        confidence=confidence
    )


def call_claude_api(diff: str, pr_info: dict, api_key: Optional[str] = None) -> ReviewResult:
    """Call Claude API for deeper analysis (optional enhancement)"""
    # This is a placeholder for Claude API integration
    # The basic version uses rule-based analysis
    # Enhanced version would call Claude API for semantic understanding
    
    prompt = f"""Analyze this PR diff and provide a code review.

PR Title: {pr_info.get('title', 'Unknown')}
PR Author: {pr_info.get('user', {}).get('login', 'Unknown')}

Diff:
```
{diff[:10000]}  # Truncate for API limits
```

Provide:
1. A 2-3 sentence summary
2. Identified risks (security, performance, maintainability)
3. Improvement suggestions
4. Confidence level (Low/Medium/High)

Format as JSON with keys: summary, risks, suggestions, confidence
"""
    
    # For now, fall back to rule-based analysis
    # Enhanced version would call: https://api.anthropic.com/v1/messages
    return analyze_diff(diff, pr_info)


def main():
    parser = argparse.ArgumentParser(
        description="Claude Code PR Review Agent",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  claude-review --pr https://github.com/owner/repo/pull/123
  claude-review --pr owner/repo/123
  claude-review --diff changes.diff --repo owner/repo --pr-title "Fix bug"

Environment:
  GITHUB_TOKEN    GitHub API token (optional, increases rate limit)
  ANTHROPIC_API_KEY   Claude API key (optional, enables semantic analysis)
"""
    )
    
    parser.add_argument("--pr", help="PR URL or short format (owner/repo/123)")
    parser.add_argument("--diff", help="Path to diff file (alternative to --pr)")
    parser.add_argument("--repo", help="Repository (owner/repo) when using --diff")
    parser.add_argument("--pr-title", help="PR title when using --diff")
    parser.add_argument("--output", "-o", help="Output file (default: stdout)")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown", help="Output format")
    parser.add_argument("--no-header", action="store_true", help="Omit markdown header")
    
    args = parser.parse_args()
    
    # Get tokens from environment
    github_token = os.environ.get("GITHUB_TOKEN")
    claude_token = os.environ.get("ANTHROPIC_API_KEY")
    
    if not args.pr and not args.diff:
        parser.error("Either --pr or --diff is required")
    
    try:
        if args.pr:
            # Parse PR URL
            owner, repo, pr_num = parse_pr_url(args.pr)
            
            # Fetch PR data
            print(f"Fetching PR #{pr_num} from {owner}/{repo}...", file=sys.stderr)
            diff = fetch_pr_diff(owner, repo, pr_num, github_token)
            pr_info = fetch_pr_info(owner, repo, pr_num, github_token)
        else:
            # Use local diff
            if not args.repo:
                parser.error("--repo is required when using --diff")
            
            with open(args.diff) as f:
                diff = f.read()
            
            pr_info = {
                "title": args.pr_title or "Local Diff Review",
                "user": {"login": "local"}
            }
            owner, repo = args.repo.split("/", 1) if "/" in args.repo else (args.repo, "unknown")
        
        # Analyze
        if claude_token:
            print("Using Claude API for semantic analysis...", file=sys.stderr)
            result = call_claude_api(diff, pr_info, claude_token)
        else:
            print("Using rule-based analysis...", file=sys.stderr)
            result = analyze_diff(diff, pr_info)
        
        # Output
        if args.format == "json":
            output = json.dumps({
                "summary": result.summary,
                "risks": result.risks,
                "suggestions": result.suggestions,
                "confidence": result.confidence
            }, indent=2)
        else:
            output = result.to_markdown()
            if args.no_header:
                output = output.replace("## 🤖 Automated PR Review\n\n", "")
        
        if args.output:
            with open(args.output, "w") as f:
                f.write(output)
            print(f"Review written to {args.output}", file=sys.stderr)
        else:
            print(output)
        
        return 0
        
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    except urllib.error.URLError as e:
        print(f"Network error: {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"Unexpected error: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())